name: KentNguyen
favicon: null
layout_spectrum: 0.5551498509012163
typography_spectrum: 0.41595876193605363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8930101993028075
  lightness: 0.0031271514017134905
  saturation: 0.1290709744207561
  rhythmicContrast: 0.29302857466973364
purpose: []
